[package]
name = "simple-bitcoin-rs"
version = "0.1.0"
authors = ["Rg <daimaldd@gmail.com>"]

[dependencies]
sha2 = "0.6.0"
time = "0.1"
leveldb-rs = "0.0.7"
tempdir = "*"
secp256k1 = "0.7.1"
hex = { git = "https://github.com/KokaKiwi/rust-hex.git"}
util_rs = {git = "https://github.com/laohanlinux/util-rs.git"}
compare = "*"
rust-base58 = "*"
bigint = "4.2.0"
rand = "*"
rust-crypto = "^0.2"
crc = "^1.0.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
quick-error = "*"
lazy_static = "0.2"

[[bin]]
path = "src/main.rs"
name = "bitcoin"
