[package]
name = "simple-bitcoin-rs"
version = "0.1.0"
authors = ["Rg <zhenghuarong@kibey.com>"]

[dependencies]
sha2 = "0.6.0"
time = "0.1"
clippy = "*"

[[bin]]
path = "src/main.rs"
name = "bitcoin"
