./build.sh create_blockchain

./build.sh send 
./build.sh send 
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
./build.sh send
